apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-100m
  labels:
    type: nfs
spec:
  storageClassName: nfs-storage
  capacity:
    storage: 100Mi
  accessModes:
  - ReadWriteOnce
  nfs: 
    server: 192.168.88.60 #
    path: /nfs/data/cc 

