apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-100m
  labels:
    type: nfs
spec:
  storageClassName: nfs-storage
  capacity:
    storage: 100Mi
  accessModes:
  - ReadWriteOnce
  nfs: ## 使用nfs存储系统
    server: 192.168.88.60 ## 没type
    path: /nfs/data/cc ### abc文件夹提前创建

