apiVersion: v1
kind: PersistentVolume
metadata:
  name: persistent-delete 
  labels:
    type: local
spec:
  persistentVolumeReclaimPolicy: Delete # 
  storageClassName: nfs-storage-delete
  capacity:
    storage: 10Mi
  accessModes:
  - ReadWriteOnce
  nfs:
    server: 192.168.88.60
    path: /nfs/data/pv-pvc-delete
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: persistent-claim
  namespace: prod
  labels:
    app: pv-pvc
spec:
  storageClassName: nfs-storage-delete
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Mi

