apiVersion: v1
kind: PersistentVolume
metadata:
  name: persistent-recycl
  labels:
    type: local
spec:
  persistentVolumeReclaimPolicy: Recycle # 
  storageClassName: nfs-storage
  capacity:
    storage: 10Mi
  accessModes:
  - ReadWriteOnce
  nfs: #
    server: 192.168.88.60 #
    path: /nfs/data/recycle #


