apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-10m-recycl
  labels:
    type: local
spec:
  persistentVolumeReclaimPolicy: Recycle # 
  storageClassName: nfs-storage
  capacity:
    storage: 10Mi
  accessModes:
  - ReadWriteOnce
  nfs: ## 使用nfs存储系统
    server: 192.168.88.60 ## 没type
    path: /nfs/data/recycle ### abc文件夹提前创建


