apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-10m
  namespace: prod 
  labels:
    app: pvc-10m
spec:
  storageClassName: nfs-storage
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Mi

