apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: stateful
  namespace: prod
spec:
  serviceName: svc-mysql
  selector:
    matchLabels:
      app: mysql
  replicas: 2 
  template:
    metadata:
      labels:
        app: mysql
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: mysql
        image: mysql:8.0.25
        securityContext: 
          runAsUser: 1000
          runAsGroup: 1000
        ports:
        - containerPort: 3306
          name: mysql-port
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: root-password
        - name: MYSQL_DATABASE
          value: "db_prod"
        - name: LANG
          value: "C.UTF-8"
        - name: LC_ALL
          value: "C.UTF-8"
        volumeMounts:
        - name: mysql-cnf
          mountPath: /etc/mysql/conf.d
        - name: mysql-data
          mountPath: /var/lib/mysql
      volumes:
        - name: mysql-cnf
          configMap: 
            name: mysql-cnf 
  volumeClaimTemplates:
  - metadata:
      name: mysql-cnf
    spec:
      storageClassName: ""
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 20Mi
  - metadata:
      name: mysql-data
    spec:
      storageClassName: ""
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 5Gi
---
apiVersion: v1
kind: Service
metadata:
  name: svc-mysql
  namespace: prod
spec:
  selector:
    app: mysql
  type: ClusterIP
  clusterIP: None 
  ports:
  - name: svc-mysql
    port: 3306  
    targetPort: 3306 
    protocol: TCP

