apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: stateful
  namespace: test
spec:
  serviceName: svc-mysql
  selector:
    matchLabels:
      app: mysql
  replicas: 2 # by default is 1
  template:
    metadata:
      labels:
        app: mysql
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: mysql
        image: mysql:8.0.25
        securityContext: ## 指定安全上下文
          runAsUser: 1000
          runAsGroup: 1000
        ports:
        - containerPort: 3306
          name: mysql-port
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "P@ssw0rd"
        - name: MYSQL_DATABASE
          value: "db_test"
        volumeMounts:
        - name: mysql-cnf
          mountPath: /etc/mysql/conf.d
        - name: mysql-data
          mountPath: /var/lib/mysql
  volumeClaimTemplates:
  - metadata:
      name: mysql-cnf
    spec:
      storageClassName: ""
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 20Mi
  - metadata:
      name: mysql-data
    spec:
      storageClassName: ""
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 5Gi
---
apiVersion: v1
kind: Service
metadata:
  name: svc-mysql
  namespace: test
spec:
  selector:
    app: mysql
  type: NodePort
  # type: ClusterIP
  # clusterIP: None ## 沒有集群ip，只能通過內部的dns訪問 mysql-cluster-0.mysql.default
  ports:
  - name: svc-mysql
    port: 3306 ## service端口
    targetPort: 3306 ## pod端口
    protocol: TCP

