apiVersion: v1
kind: Pod
metadata:
  name: "pod-taint-2"
  namespace: test 
  labels:
    app: "pod-taint-2"
spec:
  containers:
  - name: pod-taint-2
    image: "busybox"
    command: ["sleep", "3600"]
  tolerations:
  - key: "key"
    operator: "Exists"
    effect: "NoSchedule" 

