apiVersion: v1
kind: Pod
metadata:
  name: pod-softaffinity
  namespace: test
  labels:
    app: softaffinity
spec:
  containers:
  - name: softaffinity
    image: "busybox"
    command: ["sh","-c","sleep infinity"]
  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution: 
      - preference: 
          matchExpressions:
          - key: disk
            values: ["70"]
            operator: Gt
        weight: 90 
      - preference: 
          matchExpressions:
          - key: gpu
            values: ["4000"]
            operator: Gt 
        weight: 10 


