apiVersion: v1
kind: Pod
metadata:
  name: "pod-taint-1"
  namespace: test
  labels:
    app: "pod-taint-1"
spec:
  containers:
  - name: pod-taint-1
    image: "busybox"
    command: ["sleep", "3600"]
