apiVersion: v1
kind: Pod
metadata:
  name: pod-softaffinity
  namespace: test
  labels:
    app: softaffinity
spec:
  containers:
  - name: softaffinity
    image: "busybox"
    command: ["sh","-c","sleep infinity"]
  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution: ## 软性打分
      - preference: ## 指定我们喜欢的条件 shib
          matchExpressions:
          - key: disk
            values: ["70"]
            operator: Gt
        weight: 90 ## 权重 0-100
      - preference: ## 指定我们喜欢的条件
          matchExpressions:
          - key: gpu
            values: ["4000"]
            operator: Gt ## node1的gpu不满足这个条件
        weight: 10 ## 权重 0-100


