apiVersion: v1
kind: Service
metadata:
  name: cluster-fixip
  namespace: test
spec:
  selector:
    app: cluster
  clusterIP: 10.96.11.99 
  type: ClusterIP ## ClusterIP,ExternalName, NodePort, and LoadBalancer
  ports:
  - name: abc
    port: 80  #
    targetPort: 80  #
  # ports:
  # - name: abc
  #   port: 80  #
  #   targetPort: 8080  #
  # - name: redis
  #   port: 99
  #   targetPort: 6379
