apiVersion: v1
kind: Service
metadata:
  name: clusterip-none
  namespace: test
spec:
  selector:
    app: svc-stateful 
  # clusterIP: 10.96.88.99
  clusterIP: None  
  type: ClusterIP #
  ports:
  - name: abc
    port: 80  #
    targetPort: 80  #
  # ports:
  # - name: abc
  #   port: 80  #
  #   targetPort: 8080  #
  # - name: redis
  #   port: 99
  #   targetPort: 6379
  #
  #
  #

