apiVersion: v1
kind: Service
metadata:
  name: clusterip
  namespace: test
spec:
  selector:
    app: cluster
  type: ClusterIP 
  ports:
  - name: abc
    port: 80  #
    targetPort: 80  #
  # ports:
  # - name: abc
  #   port: 80  
  #   targetPort: 8080  #
  # - name: redis
  #   port: 99
  #   targetPort: 6379
