apiVersion: v1
kind: Service
metadata:
  name: no-selector
  namespace: test
spec:
  type: ClusterIP 
  ports:
  - name: abc
    port: 80  #
    targetPort: 80  #
---
apiVersion: v1
kind: Endpoints
metadata:
  name: no-selector  #
  namespace: test
subsets:
- addresses:
  - ip: 10.244.90.48 
  - ip: 10.244.133.50
  - ip: 10.244.221.7
  ports:
  - name: abc  #
    port: 80
    protocol: TCP
