apiVersion: v1
kind: LimitRange
metadata:
  name: limitrange-cpu
  namespace: prod 
spec:
  limits:
  - max:
      cpu: "800m"
      memory: "1Gi"

    min:
      cpu: "200m"
      memory: "20m"  
    type: Container

