apiVersion: v1
kind: LimitRange
metadata:
  name: cpu-min-max
  namespace: test 
spec:
  limits:
  - max:
      cpu: "800m"
      memory: "1Gi"

    min:
      cpu: "200m"
      memory: "20m"  
    type: Container

