apiVersion: batch/v1
kind: CronJob
metadata:
  name: crontab
  namespace: prod
spec:
  schedule: "*/1 * * * *"    
  jobTemplate:
    # kind: Job
    spec:  
      template:
        spec:
          containers:
          - name: hello
            image: busybox
            args:
            - /bin/sh
            - -c
            - date >> /1.txt; 
          restartPolicy: OnFailure
