apiVersion: batch/v1
kind: Job
metadata:
  namespace: test
  name: job
spec:
  completions: 7  
  parallelism: 2
  template:
    spec:
      containers:
      - name: ping
        image: busybox  
        command: ["/bin/sh","-c","ping -c 3 www.google.com"]
      restartPolicy: Never 
  # backoffLimit: 4 
  activeDeadlineSeconds: 600   
  ttlSecondsAfterFinished: 10  
