apiVersion: v1
kind: Pod
metadata:
  name: "probe-ready-1"
  namespace: prod 
  labels:
    app: "probe"
spec:
  volumes:
  - name: nginx-vol
    hostPath: 
      path: /app
  - name: nginx-html
    hostPath: 
      path: /html
  containers:
  - name: nginx
    image: "nginx"
    ports:
    - containerPort: 80
    volumeMounts:
    - name: nginx-vol
      mountPath: /app
    - name: nginx-html
      mountPath: /usr/share/nginx/html
    readinessProbe: #
      httpGet:  
        path: /abc.html  #
        port: 80
        scheme: HTTP # 
      initialDelaySeconds: 2 #
      periodSeconds: 1  #
      timeoutSeconds: 5  #
      successThreshold: 3 #
      failureThreshold: 5 #
        
    # livenessProbe:
    #   exec: ["/bin/sh","-c","sleep 30;abc "]  #
    #   initialDelaySeconds: 20 #
    #   periodSeconds: 5  #
    #   timeoutSeconds: 5  #
    #   successThreshold: 5 #
    #   failureThreshold: 5 #

    
