apiVersion: v1
kind: Pod
metadata:
  name: "probe-liveness-2"
  namespace: test 
  labels:
    app: "probe-liveness-2"
spec:
  volumes:
  - name: nginx-vol
    hostPath: 
      path: /app
  - name: nginx-html
    hostPath: 
      path: /html
  containers:
  - name: nginx
    image: "nginx"
    ports:
    - containerPort: 80
    volumeMounts:
    - name: nginx-vol
      mountPath: /app
    - name: nginx-html
      mountPath: /usr/share/nginx/html
    livenessProbe:   ##
      exec:
        command:  ["/bin/sh","-c","cat /usr/share/nginx/html/abc.html"]  #
      periodSeconds: 1  #
      timeoutSeconds: 5  #
      successThreshold: 1 #
      failureThreshold: 3 #
        

    
