apiVersion: v1
kind: Pod
metadata:
  name: "pod-startprobe"
  namespace: test 
  labels:
    app: "pod-startprobe"
spec:
  volumes:
  - name: nginx-vol
    hostPath: 
      path: /app
  - name: nginx-html
    hostPath: 
      path: /html
  containers:
  - name: nginx
    image: "nginx"
    ports:
    - containerPort: 80
    startupProbe:
      exec:
        command:  ["/bin/sh","-c","cat /app/abc"]  #
      initialDelaySeconds: 2 #
      periodSeconds: 1  #
      timeoutSeconds: 3  #
      successThreshold: 1 #
      failureThreshold: 3 #
    volumeMounts:
    - name: nginx-vol
      mountPath: /app
    - name: nginx-html
      mountPath: /usr/share/nginx/html

    
