apiVersion: v1
kind: Pod
metadata:
  name: test-env
  namespace: test
  labels:
    aa: bb
    cc: dd
spec:
  containers:
  - image: nginx
    name: nginx 
    command: 
      - /bin/bash
      - -c
      - "echo $msg;sleep 3600;"
    env:
      - name: msg
        value: "hello msg"
