apiVersion: apps/v1 ###
kind: Deployment ##
metadata:
  name:  test-deploy   
  namespace: test 
  labels:
    #dep:  test-01
    app: cluster
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 2
      maxSurge: 20
  replicas: 20 
  selector:   
    matchLabels:   
      #pod-name: nginx-01 
      app: cluster
  template:
    metadata:   
      labels:
        #pod-name: nginx-01
        app: cluster
    spec:
      containers:
      - name:  nginx
        image:  nginx:1.20.0-alpine

