apiVersion: v1
kind: Pod
metadata:
  name: multi-container
  namespace: prod
  labels:
    app: "multi-container-pod"
spec:
  volumes:    
  - name: nginx-vol
    emptyDir: {}  
  containers:  
  - name: container-1
    image: "nginx"
    volumeMounts:  
      - name: nginx-vol
        mountPath: /usr/share/nginx/html
  - name: container-2
    image: "alpine"
    command: ["/bin/sh","-c","while true;do sleep 1; date > /app/index.html;done;"]
    volumeMounts: 
      - name: nginx-vol
        mountPath: /app


  
