apiVersion: v1
kind: Pod
metadata:
  name: "pod-ifecycle-1"
  namespace: test
  labels:
    app: "pod-lifecycle-1"
    
spec:
  containers:
  - image: "nginx"
    name: pod-1
  - image: "alpine"
    name: pod-2
    command: ["/bin/sh","-c","sleep 3"]      
