apiVersion: v1
kind: Pod
metadata:
  name: lifecycle-hook
  namespace: prod 
  labels:
    app: "pod-lifecycle-hook"
    
spec:
  containers:
  - image: "nginx"
    name: nginx-hook
    lifecycle:
      postStart:
        httpGet:
          host: "10.244.133.7"
          path: "/postStart"
          port: 80
          scheme: "HTTP"
      preStop:
        httpGet: 
           host: "10.244.133.7"
           path: "/preStop"
           port: 80
           scheme: "HTTP"
