apiVersion: v1
kind: Service
metadata:
  name: svc-subdomain 
  namespace: test
spec:
  selector:
    name: cluster 
  clusterIP: None
  ports:
  - name: foo # 
    port: 1234
    targetPort: 1234
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-1
  namespace: test
  labels:
    name: cluster
spec:
  hostname: pod-1
  subdomain: svc-subdomain 
  containers:
  - image: busybox:1.28
    command:
      - sleep
      - "3600"
    name: busybox
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-2
  namespace: test
  labels:
    name: cluster
spec:
  hostname: pod-2
  subdomain: svc-subdomain
  containers:
  - image: busybox:1.28
    command:
      - sleep
      - "3600"
    name: busybox
