apiVersion: v1
kind: Pod
metadata:
  name: lifecycle-2
  namespace: prod
  labels:
    app: "pod-lifecycle-2"
spec:
  volumes:
  - name: init-vol
    emptyDir: {}
  initContainers:
  - name: init-container-01
    image: alpine
    command: ["/bin/sh","-c","echo Hello~>/app/index.html"]
    volumeMounts:
     - name: init-vol
       mountPath: /app
  containers:
  - image: "nginx"
    name: pod-1
    volumeMounts: 
     - name: init-vol
       mountPath: /usr/share/nginx/html
  - image: "alpine"
    name: pod-2 
    command: ["/bin/sh","-c","sleep 30"]      
