apiVersion: v1
kind: Pod
metadata:
  name: "pod-lifecycle-hook"
  namespace: test 
  labels:
    app: "pod-lifecycle-hook"
    
spec:
  containers:
  - image: "nginx"
    name: nginx-hook
    lifecycle:
      postStart:
        httpGet:
          host: "10.244.221.63"
          path: "/postStart"
          port: 80
          scheme: "HTTP"
      preStop:
        httpGet: 
           host: "10.244.221.63"
           path: "/preStop"
           port: 80
           scheme: "HTTP"
