apiVersion: v1
kind: Pod
metadata:
  name: mount-secret-1
  namespace: prod 
  labels:
    app: pod-mount-secret
spec:
  volumes:
  - name: pod-vol
    secret: 
      defaultMode: 0400
      secretName: "dev-db-secret"
      items:
      - key: password
        path: pwd.md  
  containers:
  - name: pod-moount-secret
    image: "busybox"
    command: ["/bin/sh","-c","sleep 3600"]
    resources:
      limits:
        cpu: 10m
      requests:  
        cpu: 5m 
    volumeMounts:
    - name: pod-vol
      mountPath: /app

