apiVersion: v1
kind: Pod
metadata:
  name: "pod-mount-time-1"
  namespace: test 
  labels:
    app: "pod-mount-time"
spec:
  containers:
  - name: pod-mount-time
    image: "busybox"
    command: ["sleep","60000"]
    volumeMounts:
    - name: localtime
      mountPath: /etc/localtime
  volumes:
  - name: localtime
    hostPath:
      path: /usr/share/zoneinfo/Asia/Taipei
      type: File
