apiVersion: v1
kind: Pod
metadata:
  name: pod-mount-secret-2
  namespace: test
  labels:
    app: pod-vol
spec:
  containers:
  - name: pod-mount-secret
    image: "busybox"
    command: ["/bin/sh","-c","sleep 3600"]
    resources:
      limits:
        cpu: 10m
      requests:  
        cpu: 5m  
    env:
    - name: MY_USR
      valueFrom:
        secretKeyRef:
          name: db-user
          key: username
    - name: POD_NAME
      valueFrom:
        fieldRef:
          fieldPath: metadata.name
    - name: Pod_limit_CPU
      valueFrom:
        resourceFieldRef:
          containerName: pod-mount-secret
          resource: limits.cpu
