apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-cephfs
  namespace: default
  labels:
    app: nginx-cdphfs
spec:
  selector:
    matchLabels:
      app: nginx-cephfs
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx-cephfs
    spec:
      # initContainers:
# - Init containers always run to completion.
# - Each init container must complete successfully befor
      containers:
        - name: nginx-deploy
          image: nginx
          volumeMounts:
            - name: localtime
              mountPath: /etc/localtime
            - name: nginx-html-storage
              mountPath: /usr/share/nginx/html
      volumes:
        - name: localtime
          hostPath:
            path: /usr/share/zoneinfo/Asia/Shanghai
        - name: nginx-html-storage
          persistentVolumeClaim:
            claimName: nginx-pv-claim
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nginx-pv-claim
  labels:
    app: nginx-deploy
spec:
  storageClassName: rook-cephfs
  accessModes:
    - ReadWriteMany ##如果是 ReadWriteOnce将会是什么效果
  resources:
    requests:
      storage: 10Mi

