apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ns-reader
rules: #
- apiGroups: [""] # "" 
  resources: ["namespaces"] #
  verbs: ["get", "watch", "list","create"] #
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: read-ns-global
subjects: #
- kind: ServiceAccount
  name: km # 'name' 
  namespace: test
  apiGroup: "" 
roleRef:
  kind: ClusterRole
  name: ns-reader
  apiGroup: rbac.authorization.k8s.io

