apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: test 
  name: pod-reader
rules:
- apiGroups: [""] # "" 
  resources: ["pods"]
  verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  # "namespace" 
  name: secret-reader
rules:
- resources: ["secrets"]
  apiGroups: [""]
  verbs: ["get", "watch", "list"]
- resources: ["configmaps"]
  apiGroups: [""]
  verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: km-pod-reader
  namespace: test
subjects:
- kind: ServiceAccount
  name: km
  namespace: test
roleRef:
  kind: Role
  name: pod-reader
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: km-secret-reader
  namespace: test
subjects:
- kind: ServiceAccount
  name: km
  namespace: test
roleRef:
  kind: ClusterRole
  name: secret-reader
  apiGroup: rbac.authorization.k8s.io
