apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: net-rule-2
  namespace: test
spec:
  podSelector:  ## 选中指定Pod
    matchLabels:
      role: db
  policyTypes:  ## 定义上面Pod的入站出站规则
  - Ingress
  - Egress
  ingress:    ## 定义入站白名单
  - from:   
    - ipBlock:
        cidr: 192.168.88.0/24
        except:
        - 192.168.88.60/32
    - namespaceSelector:
        matchLabels:
          name: net-rule
    - podSelector:
        matchLabels:
          role: frontend
    ports:
    - protocol: TCP
      port: 30736
  egress:  ## 定义出站白名单
  - to:
    - ipBlock:
        cidr: 192.168.88.0/24
    ports:
    - protocol: TCP
      port: 5978
