apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: rule-2
  namespace: prod 
spec:
  podSelector:  #
    matchLabels:
      role: db
  policyTypes:  #
  - Ingress
  - Egress
  ingress:    ##
  - from:   
    - ipBlock:
        cidr: 10.244.87.0/24
        except:
        - 10.244.87.117/32
    - namespaceSelector:
        matchLabels:
          name: net-rule
    - podSelector:
        matchLabels:
          role: frontend
    ports:
    - protocol: TCP
      port: 80
  egress:  ## 
  - to:
    - ipBlock:
        cidr: 10.244.87.117/32 
    ports:
    - protocol: TCP
      port: 5978
